# Relative Abundance {#abundance}

Here, we calculate the relative abundance for the different nodes of the migratory network. The input data for this step are:

* Abundance data (Raster)
* Population ranges (Raster or Vector)

Typically, the geographic range of a population will be stored as a vector (e.g., polygon), but in the case of a genoscape, the population ranges can be specified by a raster with q-values. For abundance data, we will use the [eBird Status and Trends](https://science.ebird.org/en/status-and-trends) data which are obtained with the [ebirdst R package](https://cornelllabofornithology.github.io/ebirdst/), but any abundance data in a raster object can be used. **Note:** We do not provide the `ebirdst` data within `mignette` - these data are publicly available and licensed by the Cornell Lab of Ornithology and can be obtained by following the appropriate directions in the above links.

## Get relative abundance for a genoscape (raster)

In the case of a *genoscape* raster with q-values, we will convert the q-values to probabilities of a pixel belonging to that population which is used to weight the abundance values. This is done with a single function `get_genoscape_abunds()`, and outputs a two-column matrix with the population names and the relative abundance of each population. Below, we provide an example with the genoscape as a SpatRaster (`genoscape`) and the ebirdst abundance data as a SpatRaster (`abunds`; obtained from the links above).

```r
genoscape_abunds <- get_genoscape_abunds(genoscape = amre_genoscape, abunds = abunds)
```

## Get relative abundance for a vector

In the case of vector file delineating populations, we sum abundance across the range of each population. This is done with a single function `get_vector_abunds()`, and outputs a two-column matrix with the population names and the relative abundance of each population. The example below provides the nonbreeding ecoregions file as a SpatVector (`winter_regions`) and the ebirdst abundance data as a SpatRaster (`abunds`)

```r
winter_abunds <- get_vector_abunds(populations = nonbreeding_regions_subset, abunds = abunds)
```

## Combine the abundance data

As you'll see in the next section, these data are one of the primary inputs into the migratory network model and we combine the relative abundance data sets across the breeding and nonbreeding nodes with the following code. The final product is what we provide in this package

```r
amre_abundance <- rbind(genoscape_abunds, winter_abunds) %>%
  as_tibble() %>%
  mutate(Relative_abundance = round(as.numeric(Relative_abundance)))
amre_abundance
```

```{r, echo = F}
knitr::kable(mignette::amre_abundance)
```

Now on to creating the [migratory network model](#connectivity).
