# Network visualization {#visualization}

We provide functions for basic visualization of the network (`net_create()` and `net_draw()`). A threshold can be set to remove very weak connectivity for better visualizing the network as shown below.

```{r}
bnode_names <- c("WB", "NT", "ST")
wnode_names <- c("ALM", "CAR", "AONU")
# set threshold for not visualizing minimal connectivity
amre_conn_test <- mignette::amre_conn
amre_conn_test[amre_conn_test < 0.01] <- 0
net <- mignette::net_create(amre_conn_test, 
                            node.names = list(bnode_names, wnode_names))
#set the display size range for nodes (min and max), default 1-10
net$display_par$node_size_scale<-c(5,20)
#set the display size range for edges (min and max), default 1-10
net$display_par$edge_size_scale<-c(1,5)
plot(mignette::net_draw(net))
```

In this visualization, node size corresponds to the amount of connectivity with that population and edge size corresponds to the amount of connectivity between the populations. By default, breeding populations are in the top row (red) and nonbreeding populations are in the bottom row (blue). 

This sums up the basics of creating and visualizing a migratory network. We encourage users to explore and build upon the visualization tools we provide (e.g. overlay the migratory networks on geographic ranges) - the options are endless, enjoy!
